### ISSUE TITLE
Traduzir expressão "Arrow Functions"?

### ISSUE THREAD

**Issue by breakzplatform** [joselitojunior1/aprenda-angular2#1]
Essa issue é pra discutir se devemos ou não traduzir o termo, bem como qual a melhor maneira de traduzi-lo.

Função seta? Função de seta?

**Comment by Cisneiros** [comment]
Eu gosto do termo "seta gorda". Mas acho que "função seta" faz sentido pq a gente traduz lambda functions como função lambda.

**Comment by thompsonemerson** [comment]
Eu particularmente prefiro Arrow Function.

**Comment by breakzplatform** [comment]
@thompsonemerson mas você prefere porquê, meu jovem?

**Comment by Cisneiros** [comment]
Eu não tenho nenhum problema com Arrow Function porque eu na verdade não tenho problema em ler em inglês. Mas isso não é verdade para todos, e em especial pelo que entendi a proposta da página é ser conteúdo em português. Se a gente traduz _function_ pra _função_, por que não traduzir _arrow function_? Dado que exista uma tradução, não vejo por que não usar numa documentação em português. (:

**Comment by thompsonemerson** [comment]
É que você vai encontrar muito conteúdo na internet, mesmo em pt a galera usa o termo Arrow Function.
Em palestras e workshops também é citado muito o Arrow Function, então fica mais fácil de similar saca?

**Comment by breakzplatform** [comment]
Vamos manter a expressão em inglês, dado ao uso geral dela mesmo em tutoriais em português.
